### ISSUE TITLE
CouchDB 3.3.1 crashing on OS X

### ISSUE THREAD

**Issue by nenadra** [apache/couchdb#4372]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

I was running 3.2.x normally. Yesterday I updated to 3.3.0 and then to 3.3.1 and the same happened.
Running a local nginx web server with CouchDB database. 
I opened the Console to check the crashes and there were like 30 records of the same process crashing at the same time:

Process:               couchjs [1983]
Path:                  /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/couchjs

So I was looking more into the report and apparently this was the reason:

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/spidermonkey/lib/libmozjs-91.dylib'
Referenced from: '/Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/couchjs'
Reason: tried: '/usr/local/opt/spidermonkey/lib/libmozjs-91.dylib' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

I installed spidermonkey with homebrew now. I am testing to see if the crash will occur again or not.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.3.1
* Browser name and version: Safari 16.2
* Operating system and version: OS X 12.6.2

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by big-r81** [comment]
If you install Spidermonkey v91 with homebrew, the error should be gone.

**Comment by nenadra** [comment]
Thanks, I did that and it is OK now

**Comment by janl** [comment]
this is a bug in the binary, thanks for filing!

**Comment by nenadra** [comment]
you're welcome!

**Comment by jonathanwork** [comment]
[info] 2023-03-10T22:17:19.187164Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27265.3> died normal
[error] 2023-03-10T22:17:19.187259Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27265.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.190168Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27261.3> died normal
[error] 2023-03-10T22:17:19.190274Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27261.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.203529Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27267.3> died normal
[error] 2023-03-10T22:17:19.203605Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27267.3> :: {os_process_error,{exit_status,134}}
[error] 2023-03-10T22:17:19.310265Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27274.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.310379Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27274.3> died normal
[info] 2023-03-10T22:17:19.311886Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27272.3> died normal
[error] 2023-03-10T22:17:19.312112Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27272.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.370408Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27276.3> died {badarg,[{erlang,port_command,[#Port<0.79505>,[<<"[\"reset\",{\"reduce_limit\":true,\"timeout\":5000}]">>,10]],[{error_info,#{module => erl_erts_errors}}]},{couch_os_process,writeline,2,[{file,"src/couch_os_process.erl"},{line,65}]},{couch_os_process,writejson,2,[{file,"src/couch_os_process.erl"},{line,102}]},{couch_os_process,handle_call,3,[{file,"src/couch_os_process.erl"},{line,209}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1149}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1178}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
[error] 2023-03-10T22:17:19.371532Z couchdb@localhost <0.27276.3> -------- gen_server <0.27276.3> terminated with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"[\"reset\",{\"reduce_limit\":true,\"timeout\":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240)
  last msg: redacted
     state: {os_proc,"./bin/couchjs ./share/server/main.js",#Port<0.79505>,fun couch_os_process:writejson/2,fun couch_os_process:readjson/1,5000,300000}
    extra: [<0.27621.1>,[{gen,do_call,4,[{file,"gen.erl"},{line,237}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,381}]},{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,54}]},{couch_query_servers,proc_prompt,2,[{file,"src/couch_query_servers.erl"},{line,581}]},{couch_query_servers,get_os_process,1,[{file,"src/couch_query_servers.erl"},{line,698}]},{couch_mrview,validate,2,[{file,"src/couch_mrview.erl"},{line,241}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1442}]},{couch_db,validate_ddoc,2,[{file,"src/couch_db.erl"},{line,934}]}]]
[error] 2023-03-10T22:17:19.375409Z couchdb@localhost <0.27276.3> -------- gen_server <0.27276.3> terminated with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"[\"reset\",{\"reduce_limit\":true,\"timeout\":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240)
  last msg: redacted
     state: {os_proc,"./bin/couchjs ./share/server/main.js",#Port<0.79505>,fun couch_os_process:writejson/2,fun couch_os_process:readjson/1,5000,300000}
    extra: [<0.27621.1>,[{gen,do_call,4,[{file,"gen.erl"},{line,237}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,381}]},{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,54}]},{couch_query_servers,proc_prompt,2,[{file,"src/couch_query_servers.erl"},{line,581}]},{couch_query_servers,get_os_process,1,[{file,"src/couch_query_servers.erl"},{line,698}]},{couch_mrview,validate,2,[{file,"src/couch_mrview.erl"},{line,241}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1442}]},{couch_db,validate_ddoc,2,[{file,"src/couch_db.erl"},{line,934}]}]]
[error] 2023-03-10T22:17:19.375651Z couchdb@localhost <0.27276.3> -------- CRASH REPORT Process  (<0.27276.3>) with 0 neighbors crashed with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"[\"reset\",{\"reduce_limit\":true,\"timeout\":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27275.3>], message_queue_len: 1, links: [<0.274.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 859
[error] 2023-03-10T22:17:19.375835Z couchdb@localhost <0.27276.3> -------- CRASH REPORT Process  (<0.27276.3>) with 0 neighbors crashed with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"[\"reset\",{\"reduce_limit\":true,\"timeout\":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27275.3>], message_queue_len: 1, links: [<0.274.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 859
[info] 2023-03-10T22:17:19.399625Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27280.3> died normal
[error] 2023-03-10T22:17:19.399724Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27280.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.426358Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27282.3> died normal
[error] 2023-03-10T22:17:19.426495Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27282.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.426556Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27285.3> died normal
[error] 2023-03-10T22:17:19.426625Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27285.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.495635Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27289.3> died normal
[error] 2023-03-10T22:17:19.495705Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27289.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.499630Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27292.3> died normal
[error] 2023-03-10T22:17:19.499696Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27292.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.507891Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27294.3> died normal
[error] 2023-03-10T22:17:19.507972Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27294.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.556673Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27298.3> died normal
[error] 2023-03-10T22:17:19.557024Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27298.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.570883Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27301.3> died normal
[error] 2023-03-10T22:17:19.571173Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27301.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.571993Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27303.3> died normal
[error] 2023-03-10T22:17:19.574316Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27303.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.670434Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27310.3> died normal
[error] 2023-03-10T22:17:19.670522Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27310.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.671444Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27308.3> died normal
[error] 2023-03-10T22:17:19.671505Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27308.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.678139Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27312.3> died normal
[error] 2023-03-10T22:17:19.678254Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27312.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.712932Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27319.3> died normal
[error] 2023-03-10T22:17:19.713024Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27319.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.713697Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27317.3> died normal
[error] 2023-03-10T22:17:19.713776Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27317.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.724381Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27321.3> died normal
[error] 2023-03-10T22:17:19.724652Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27321.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.759664Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27326.3> died normal
[error] 2023-03-10T22:17:19.759856Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27326.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.763217Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27328.3> died normal
[error] 2023-03-10T22:17:19.763877Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27328.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.773185Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27330.3> died normal
[error] 2023-03-10T22:17:19.773278Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27330.3> :: {os_process_error,{exit_status,134}}
[error] 2023-03-10T22:17:19.806338Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27337.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.806798Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27337.3> died normal
[info] 2023-03-10T22:17:19.807139Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27334.3> died normal
[error] 2023-03-10T22:17:19.807190Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27334.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.826525Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27339.3> died normal
[error] 2023-03-10T22:17:19.826607Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27339.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.871561Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27348.3> died epipe
[info] 2023-03-10T22:17:19.872111Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27345.3> died normal
[error] 2023-03-10T22:17:19.872341Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27345.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.873195Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27343.3> died normal
[error] 2023-03-10T22:17:19.873315Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27343.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.943320Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27353.3> died normal
[error] 2023-03-10T22:17:19.943404Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27353.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.956781Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27355.3> died normal
[error] 2023-03-10T22:17:19.956888Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27355.3> :: {os_process_error,{exit_status,134}}
[error] 2023-03-10T22:17:19.974194Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27357.3> :: {os_process_error,{exit_status,134}}
[info] 2023-03-10T22:17:19.974266Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27357.3> died normal
[info] 2023-03-10T22:17:19.993030Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27361.3> died normal


mine produces this error and fries up the computer of mac os big sur

**Comment by jonathanwork** [comment]
> [info] 2023-03-10T22:17:19.187164Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27265.3> died normal [error] 2023-03-10T22:17:19.187259Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27265.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.190168Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27261.3> died normal [error] 2023-03-10T22:17:19.190274Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27261.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.203529Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27267.3> died normal [error] 2023-03-10T22:17:19.203605Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27267.3> :: {os_process_error,{exit_status,134}} [error] 2023-03-10T22:17:19.310265Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27274.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.310379Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27274.3> died normal [info] 2023-03-10T22:17:19.311886Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27272.3> died normal [error] 2023-03-10T22:17:19.312112Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27272.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.370408Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27276.3> died {badarg,[{erlang,port_command,[#Port<0.79505>,[<<"["reset",{"reduce_limit":true,"timeout":5000}]">>,10]],[{error_info,#{module => erl_erts_errors}}]},{couch_os_process,writeline,2,[{file,"src/couch_os_process.erl"},{line,65}]},{couch_os_process,writejson,2,[{file,"src/couch_os_process.erl"},{line,102}]},{couch_os_process,handle_call,3,[{file,"src/couch_os_process.erl"},{line,209}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,1149}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1178}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]} [error] 2023-03-10T22:17:19.371532Z couchdb@localhost <0.27276.3> -------- gen_server <0.27276.3> terminated with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"["reset",{"reduce_limit":true,"timeout":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240) last msg: redacted state: {os_proc,"./bin/couchjs ./share/server/main.js",#Port<0.79505>,fun couch_os_process:writejson/2,fun couch_os_process:readjson/1,5000,300000} extra: [<0.27621.1>,[{gen,do_call,4,[{file,"gen.erl"},{line,237}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,381}]},{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,54}]},{couch_query_servers,proc_prompt,2,[{file,"src/couch_query_servers.erl"},{line,581}]},{couch_query_servers,get_os_process,1,[{file,"src/couch_query_servers.erl"},{line,698}]},{couch_mrview,validate,2,[{file,"src/couch_mrview.erl"},{line,241}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1442}]},{couch_db,validate_ddoc,2,[{file,"src/couch_db.erl"},{line,934}]}]] [error] 2023-03-10T22:17:19.375409Z couchdb@localhost <0.27276.3> -------- gen_server <0.27276.3> terminated with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"["reset",{"reduce_limit":true,"timeout":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240) last msg: redacted state: {os_proc,"./bin/couchjs ./share/server/main.js",#Port<0.79505>,fun couch_os_process:writejson/2,fun couch_os_process:readjson/1,5000,300000} extra: [<0.27621.1>,[{gen,do_call,4,[{file,"gen.erl"},{line,237}]},{gen_server,call,3,[{file,"gen_server.erl"},{line,381}]},{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,54}]},{couch_query_servers,proc_prompt,2,[{file,"src/couch_query_servers.erl"},{line,581}]},{couch_query_servers,get_os_process,1,[{file,"src/couch_query_servers.erl"},{line,698}]},{couch_mrview,validate,2,[{file,"src/couch_mrview.erl"},{line,241}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1442}]},{couch_db,validate_ddoc,2,[{file,"src/couch_db.erl"},{line,934}]}]] [error] 2023-03-10T22:17:19.375651Z couchdb@localhost <0.27276.3> -------- CRASH REPORT Process (<0.27276.3>) with 0 neighbors crashed with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"["reset",{"reduce_limit":true,"timeout":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27275.3>], message_queue_len: 1, links: [<0.274.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 859 [error] 2023-03-10T22:17:19.375835Z couchdb@localhost <0.27276.3> -------- CRASH REPORT Process (<0.27276.3>) with 0 neighbors crashed with reason: bad argument in call to erlang:port_command(#Port<0.79505>, [<<"["reset",{"reduce_limit":true,"timeout":5000}]">>,10]) at couch_os_process:writeline/2(line:65) <= couch_os_process:writejson/2(line:102) <= couch_os_process:handle_call/3(line:209) <= gen_server:try_handle_call/4(line:1149) <= gen_server:handle_msg/6(line:1178) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.27275.3>], message_queue_len: 1, links: [<0.274.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 859 [info] 2023-03-10T22:17:19.399625Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27280.3> died normal [error] 2023-03-10T22:17:19.399724Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27280.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.426358Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27282.3> died normal [error] 2023-03-10T22:17:19.426495Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27282.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.426556Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27285.3> died normal [error] 2023-03-10T22:17:19.426625Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27285.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.495635Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27289.3> died normal [error] 2023-03-10T22:17:19.495705Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27289.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.499630Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27292.3> died normal [error] 2023-03-10T22:17:19.499696Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27292.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.507891Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27294.3> died normal [error] 2023-03-10T22:17:19.507972Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27294.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.556673Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27298.3> died normal [error] 2023-03-10T22:17:19.557024Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27298.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.570883Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27301.3> died normal [error] 2023-03-10T22:17:19.571173Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27301.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.571993Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27303.3> died normal [error] 2023-03-10T22:17:19.574316Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27303.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.670434Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27310.3> died normal [error] 2023-03-10T22:17:19.670522Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27310.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.671444Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27308.3> died normal [error] 2023-03-10T22:17:19.671505Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27308.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.678139Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27312.3> died normal [error] 2023-03-10T22:17:19.678254Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27312.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.712932Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27319.3> died normal [error] 2023-03-10T22:17:19.713024Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27319.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.713697Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27317.3> died normal [error] 2023-03-10T22:17:19.713776Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27317.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.724381Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27321.3> died normal [error] 2023-03-10T22:17:19.724652Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27321.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.759664Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27326.3> died normal [error] 2023-03-10T22:17:19.759856Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27326.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.763217Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27328.3> died normal [error] 2023-03-10T22:17:19.763877Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27328.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.773185Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27330.3> died normal [error] 2023-03-10T22:17:19.773278Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27330.3> :: {os_process_error,{exit_status,134}} [error] 2023-03-10T22:17:19.806338Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27337.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.806798Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27337.3> died normal [info] 2023-03-10T22:17:19.807139Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27334.3> died normal [error] 2023-03-10T22:17:19.807190Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27334.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.826525Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27339.3> died normal [error] 2023-03-10T22:17:19.826607Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27339.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.871561Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27348.3> died epipe [info] 2023-03-10T22:17:19.872111Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27345.3> died normal [error] 2023-03-10T22:17:19.872341Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27345.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.873195Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27343.3> died normal [error] 2023-03-10T22:17:19.873315Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27343.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.943320Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27353.3> died normal [error] 2023-03-10T22:17:19.943404Z couchdb@localhost <0.27621.1> -------- OS Process Error <0.27353.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.956781Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27355.3> died normal [error] 2023-03-10T22:17:19.956888Z couchdb@localhost <0.7281.0> -------- OS Process Error <0.27355.3> :: {os_process_error,{exit_status,134}} [error] 2023-03-10T22:17:19.974194Z couchdb@localhost <0.661.0> f66c84532b OS Process Error <0.27357.3> :: {os_process_error,{exit_status,134}} [info] 2023-03-10T22:17:19.974266Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27357.3> died normal [info] 2023-03-10T22:17:19.993030Z couchdb@localhost <0.274.0> -------- couch_proc_manager <0.27361.3> died normal
> 
> mine produces this error and fries up the computer of mac os big sur


- figured out what it was 
- curl -X PUT 'http://admin:pass@127.0.0.1:5984/_replicator'
- {"ok":true}
- curl -X PUT 'http://admin:pass@127.0.0.1:5984/_users'
- {"ok":true}
- this just solved my problem thanks

**Comment by janl** [comment]
should be fixed in 3.2.3 and 3.3.2 released today

- https://blog.couchdb.org/2023/04/25/3-2-3-3-3-2/
- https://github.com/janl/build-couchdb-mac/commit/8dad21c257e307e7feae7ca6dd86d778ac7d624f

**Comment by mattpr** [comment]
This is still happening on macOS BigSur with official `3.3.3-2` binary when trying to replicate from a remote couch on x86_64 Ubuntu running `3.2.2` (errors start and replication never recovers after just a few documents...replication state is stuck in "running" forever until couch is killed).

I ensured all couch related processes were dead.  Cleared data folder.  Reinstalled from the downloaded binary, set a new password and ensured single-node dbs were added.

```
rm -rf ~/Library/Application\ Support/CouchDB2
curl -X PUT http://admin:password@127.0.0.1:5984/_users
curl -X PUT http://admin:password@127.0.0.1:5984/_replicator

```

Logs just overflow with stuff like the following...

```
[info] 2024-02-01T15:16:23.306769Z couchdb@localhost <0.292.0> -------- couch_proc_manager <0.15052.0> died normal
[info] 2024-02-01T15:16:23.308199Z couchdb@localhost <0.292.0> -------- couch_proc_manager <0.15050.0> died normal
[error] 2024-02-01T15:16:23.308261Z couchdb@localhost <0.14603.0> -------- OS Process Error <0.15050.0> :: {os_process_error,{exit_status,134}}
[info] 2024-02-01T15:16:23.327742Z couchdb@localhost <0.292.0> -------- couch_proc_manager <0.15058.0> died normal
[error] 2024-02-01T15:16:23.328449Z couchdb@localhost <0.904.0> -------- OS Process Error <0.15058.0> :: {os_process_error,{exit_status,134}}
[info] 2024-02-01T15:16:23.329652Z couchdb@localhost <0.292.0> -------- couch_proc_manager <0.15056.0> died normal
[error] 2024-02-01T15:16:23.329709Z couchdb@localhost <0.901.0> -------- OS Process Error <0.15056.0> :: {os_process_error,{exit_status,134}}
[info] 2024-02-01T15:16:23.341202Z couchdb@localhost <0.292.0> -------- couch_proc_manager <0.15061.0> died normal
[error] 2024-02-01T15:16:23.341302Z couchdb@localhost <0.2045.0> -------- OS Process Error <0.15061.0> :: {os_process_error,{exit_status,134}}
```

Installing with homebrew seems to resolve the issue.  So I guess just more problems with the official mac binary.
